name: Test & Lint
on: [push, pull_request]

env:
  ENV: production
  NODE_VERSION: 20

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Run tests
        run: yarn test
